# Generated by Django 6.0.4 on 2026-04-09 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Название')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Название')),
                ('info', models.TextField(blank=True, verbose_name='Информация о товаре')),
                ('price', models.IntegerField(verbose_name='Цена')),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/%Y/%m/%d/', verbose_name='Изображение товара')),
                ('in_stock', models.IntegerField(verbose_name='В наличии')),
                ('warranty', models.IntegerField(verbose_name='Гарантия')),
                ('categories', models.ManyToManyField(blank=True, related_name='products', to='product.category')),
            ],
        ),
    ]
