# Generated by Django 6.0.5 on 2026-05-29 17:34

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_initial'),
        ('catalog', '0002_category_icon'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # 1. Безопасные изменения опций и удаление старого индекса
        migrations.AlterModelOptions(
            name='cart',
            options={'verbose_name': 'Корзина', 'verbose_name_plural': 'Корзины'},
        ),
        migrations.AlterModelOptions(
            name='cartitem',
            options={'ordering': ['-created_at'], 'verbose_name': 'Позиция корзины',
                     'verbose_name_plural': 'Позиции корзины'},
        ),
        migrations.AlterModelOptions(
            name='favorite',
            options={'ordering': ['-added_at'], 'verbose_name': 'Избранное', 'verbose_name_plural': 'Избранное'},
        ),
        migrations.RemoveIndex(
            model_name='cartitem',
            name='cart_cartit_cart_id_4bd8c3_idx',
        ),

        # 2. 🔑 КЛЮЧЕВОЕ: Сначала добавляем поле user!
        migrations.AddField(
            model_name='cartitem',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='cart_items',
                                    to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cartitem',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),

        # 3. Обновляем зависимости полей
        migrations.AlterField(
            model_name='cart',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                       related_name='cart', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.product'),
        ),

        # 4. 🔑 Теперь можно менять уникальность и добавлять индекс (поле user уже существует!)
        migrations.AlterUniqueTogether(
            name='cartitem',
            unique_together={('user', 'product')},
        ),
        migrations.AddIndex(
            model_name='cartitem',
            index=models.Index(fields=['user', 'product'], name='cart_cartit_user_id_7e0c79_idx'),
        ),

        # 5. В самом конце удаляем старое поле cart
        migrations.RemoveField(
            model_name='cartitem',
            name='cart',
        ),
    ]
