# Generated by Django 6.0.5 on 2026-05-29 17:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0002_category_icon'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='banners/%Y/%m/%d/', verbose_name='Изображение баннера')),
                ('overlay_color', models.CharField(default='rgba(0,0,0,0.3)', help_text='Прозрачное наложение на изображение (HEX или RGBA)', max_length=7, verbose_name='Цвет наложения')),
                ('title', models.CharField(blank=True, max_length=100, verbose_name='Заголовок')),
                ('subtitle', models.CharField(blank=True, max_length=200, verbose_name='Подзаголовок')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('button_text', models.CharField(blank=True, default='Подробнее', max_length=50, verbose_name='Текст кнопки')),
                ('button_color', models.CharField(default='#ff6b00', help_text='HEX цвет (например, #ff6b00)', max_length=7, verbose_name='Цвет кнопки')),
                ('link_type', models.CharField(choices=[('category', 'Категория'), ('product', 'Товар'), ('custom', 'Произвольный URL'), ('none', 'Без ссылки')], default='category', max_length=10, verbose_name='Тип ссылки')),
                ('link_url', models.URLField(blank=True, help_text='Если выбран тип "Произвольный URL"', verbose_name='Произвольный URL')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('order', models.PositiveIntegerField(default=0, help_text='Чем меньше число, тем выше баннер', verbose_name='Порядок')),
                ('start_date', models.DateTimeField(blank=True, help_text='Если не указано, баннер показывается всегда', null=True, verbose_name='Дата начала')),
                ('end_date', models.DateTimeField(blank=True, help_text='Если не указано, баннер показывается всегда', null=True, verbose_name='Дата окончания')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('link_category', models.ForeignKey(blank=True, help_text='Если выбран тип "Категория"', null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.category', verbose_name='Категория')),
                ('link_product', models.ForeignKey(blank=True, help_text='Если выбран тип "Товар"', null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.product', verbose_name='Товар')),
                ('products', models.ManyToManyField(blank=True, help_text='Товары, участвующие в этой акции', related_name='banners', to='catalog.product', verbose_name='Товары акции')),
            ],
            options={
                'verbose_name': 'Баннер',
                'verbose_name_plural': 'Баннеры',
                'ordering': ['order', '-created_at'],
                'indexes': [models.Index(fields=['is_active', '-order'], name='main_banner_is_acti_374337_idx')],
            },
        ),
    ]
