# Generated by Django 6.0.5 on 2026-05-29 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='overlay_color',
            field=models.CharField(default='rgba(0,0,0,0.3)', help_text='Прозрачное наложение на изображение (HEX или RGBA)', max_length=30, verbose_name='Цвет наложения'),
        ),
    ]
