# Generated by Django 6.0.5 on 2026-05-31 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='nickname',
            field=models.CharField(blank=True, help_text='Отображается в отзывах и комментариях вместо email', max_length=50, verbose_name='Никнейм'),
        ),
    ]
