# Generated by Django 6.0.4 on 2026-05-11 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Название')),
                ('slug', models.SlugField(blank=True, null=True, verbose_name='URL-метка')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=150, verbose_name='Название')),
                ('info', models.TextField(blank=True, verbose_name='Краткая информация / характеристики')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/%Y/%m/%d/', verbose_name='Основное изображение')),
                ('in_stock', models.PositiveIntegerField(default=0, verbose_name='Остаток на складе')),
                ('warranty', models.CharField(blank=True, default='12 месяцев', max_length=50, verbose_name='Гарантия')),
                ('slug', models.SlugField(blank=True, verbose_name='URL-метка')),
                ('sku', models.CharField(blank=True, db_index=True, max_length=50, null=True, unique=True, verbose_name='Артикул')),
                ('description', models.TextField(blank=True, verbose_name='Полное описание')),
                ('old_price', models.DecimalField(blank=True, decimal_places=2, help_text='Заполните для отображения скидки', max_digits=10, null=True, verbose_name='Старая цена')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Опубликован')),
                ('is_new', models.BooleanField(db_index=True, default=False, verbose_name='Новинка')),
                ('is_hit', models.BooleanField(db_index=True, default=False, verbose_name='Хит продаж')),
                ('brand', models.CharField(blank=True, db_index=True, max_length=100, verbose_name='Бренд / Производитель')),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Вес (кг)')),
                ('views', models.PositiveIntegerField(default=0, editable=False, verbose_name='Просмотры')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('categories', models.ManyToManyField(blank=True, related_name='products', to='catalog.category', verbose_name='Категории')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['slug'], name='catalog_pro_slug_2b1eb6_idx'), models.Index(fields=['price'], name='catalog_pro_price_2d2a4c_idx'), models.Index(fields=['is_active', 'is_hit'], name='catalog_pro_is_acti_c48ff9_idx'), models.Index(fields=['brand'], name='catalog_pro_brand_f6911e_idx')],
            },
        ),
    ]
