# Generated by Django 6.0.4 on 2026-05-14 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='icon',
            field=models.CharField(blank=True, default='bi-box', max_length=50, verbose_name='Иконка (Bootstrap)'),
        ),
    ]
