# Generated by Django 6.0.5 on 2026-05-29 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_category_icon'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='product',
            name='catalog_pro_is_acti_c48ff9_idx',
        ),
        migrations.AddField(
            model_name='product',
            name='force_hit',
            field=models.BooleanField(default=False, help_text='Игнорировать авто-расчёт', verbose_name='🔥 Принудительно хит'),
        ),
        migrations.AddField(
            model_name='product',
            name='force_new',
            field=models.BooleanField(default=False, help_text='Игнорировать авто-расчёт', verbose_name='✨ Принудительно новинка'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['is_active', 'created_at'], name='catalog_pro_is_acti_00391f_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['-views'], name='catalog_pro_views_ece920_idx'),
        ),
        migrations.RemoveField(
            model_name='product',
            name='is_hit',
        ),
        migrations.RemoveField(
            model_name='product',
            name='is_new',
        ),
    ]
