# Generated by Django 6.0.5 on 2026-05-30 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_remove_product_catalog_pro_is_acti_c48ff9_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='specifications',
            field=models.JSONField(blank=True, default=dict, null=True, verbose_name='Характеристики'),
        ),
    ]
