# Generated by Django 6.0.5 on 2026-05-31 00:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='text',
        ),
        migrations.RemoveField(
            model_name='review',
            name='title',
        ),
        migrations.AddField(
            model_name='review',
            name='comment',
            field=models.TextField(default=1, help_text='Ваш подробный отзыв', verbose_name='Комментарий'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='review',
            name='cons',
            field=models.TextField(blank=True, help_text='Что не понравилось?', verbose_name='Недостатки'),
        ),
        migrations.AddField(
            model_name='review',
            name='has_issue',
            field=models.BooleanField(default=False, verbose_name='Есть проблема с описанием'),
        ),
        migrations.AddField(
            model_name='review',
            name='issue_description',
            field=models.TextField(blank=True, help_text='Опишите, что не соответствует', verbose_name='Описание проблемы'),
        ),
        migrations.AddField(
            model_name='review',
            name='pros',
            field=models.TextField(blank=True, help_text='Что понравилось?', verbose_name='Достоинства'),
        ),
        migrations.CreateModel(
            name='ReviewAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='reviews/%Y/%m/%d/', verbose_name='Файл')),
                ('file_type', models.CharField(choices=[('image', 'Изображение'), ('video', 'Видео')], max_length=10, verbose_name='Тип')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='catalog.review')),
            ],
            options={
                'verbose_name': 'Вложение отзыва',
                'verbose_name_plural': 'Вложения отзывов',
            },
        ),
    ]
