# Generated by Django 6.0.5 on 2026-06-01 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_productimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='variant_group',
            field=models.CharField(blank=True, db_index=True, help_text="Одинаковое значение связывает товары. Например: 'kingston-a400'", max_length=100, null=True, verbose_name='Группа вариантов'),
        ),
    ]
