# Generated by Django 6.0.5 on 2026-06-02 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_alter_category_options_category_parent'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название акции')),
                ('slug', models.SlugField(unique=True, verbose_name='URL-метка')),
                ('description', models.TextField(blank=True, verbose_name='Описание акции')),
                ('discount_percent', models.PositiveIntegerField(blank=True, help_text='Общая скидка на акцию (необязательно)', null=True, verbose_name='Скидка %')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('start_date', models.DateTimeField(auto_now_add=True, verbose_name='Начало акции')),
                ('end_date', models.DateTimeField(blank=True, null=True, verbose_name='Конец акции')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('products', models.ManyToManyField(related_name='promotions', to='catalog.product', verbose_name='Товары в акции')),
            ],
            options={
                'verbose_name': 'Акция',
                'verbose_name_plural': 'Акции',
                'ordering': ['-created_at'],
            },
        ),
    ]
