# Generated by Django 6.0.5 on 2026-06-02 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0011_promotion'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='promotion',
            options={'ordering': ['order', '-created_at'], 'verbose_name': 'Акция', 'verbose_name_plural': 'Акции'},
        ),
        migrations.AddField(
            model_name='promotion',
            name='banner_color',
            field=models.CharField(default='#0d6efd', help_text='Цвет фона если нет изображения (например: #0d6efd)', max_length=7, verbose_name='Цвет фона'),
        ),
        migrations.AddField(
            model_name='promotion',
            name='banner_image',
            field=models.ImageField(blank=True, help_text='Основное изображение для карусели (рекомендуемый размер: 1200x450px)', null=True, upload_to='promotions/banners/', verbose_name='Баннер акции'),
        ),
        migrations.AddField(
            model_name='promotion',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Меньшее число = выше в списке', verbose_name='Порядок отображения'),
        ),
    ]
